// <auto-generated />
using System;
using EntityFrameworkTestProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkTestProject.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20200730111313_CreateSchoolDB")]
    partial class CreateSchoolDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFrameworkTestProject.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId1")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentId1");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EntityFrameworkTestProject.Student", b =>
                {
                    b.HasOne("EntityFrameworkTestProject.Student", null)
                        .WithMany("Students")
                        .HasForeignKey("StudentId1");
                });
#pragma warning restore 612, 618
        }
    }
}
